// Map of icon components to their display names
export const techNameMap = {
  SiReact: "React.js",
  SiNextdotjs: "Next.js",
  SiTypescript: "TypeScript",
  SiTailwindcss: "Tailwind CSS",
  SiShadcnui: "Shadcn UI",
  SiPostgresql: "PostgreSQL",
  SiPrisma: "Prisma",
  SiDrizzle: "Drizzle ORM",
  SiZod: "Zod",
  SiNodedotjs: "Node.js",
  SiExpress: "Express",
  SiCss3: "CSS3",
  SiThreedotjs: "Three.js",
  SiDocker: "Docker",
  SiNginx: "NGINX",
  SiDigitalocean: "DigitalOcean",
  SiCplusplus: "C++",
  SiCmake: "CMake",
  SiXml: "XML",
  SiPython: "Python",
  SiNumpy: "NumPy",
  SiAwslambda: "AWS Lambda",
  SiReacthookform: "React-Hook-Form",
  SiClerk: "Clerk",
  SiTwilio: "Twilio",
  SiLinux: "Linux",
  SiVercel: "Vercel",
  FaAws: "AWS",
  SiAmazonec2: "AWS EC2",
  SiAmazonrds: "AWS RDS",
  FaJava: "Java",
  SiMysql: "MySQL",
  SiSpringboot: "Spring Boot",
  JavalinIcon: "Javalin",
};
